CREATE TABLE app_private.offering_proposals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), proposer_user_id uuid NOT NULL REFERENCES neon_auth."user"(id), course_id uuid NOT NULL REFERENCES app_private.courses(id), academic_year integer NOT NULL, semester text NOT NULL, section text NOT NULL, instructor_name text, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')), resolved_by uuid REFERENCES neon_auth."user"(id), resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
--> statement-breakpoint
ALTER TABLE app_private.offering_proposals ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE FUNCTION api.create_offering_proposal(p_course_id uuid,p_academic_year integer,p_semester text,p_section text,p_instructor_name text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=app_private,pg_temp AS $$ DECLARE v_id uuid; BEGIN IF auth.user_id() IS NULL THEN RAISE EXCEPTION 'authentication required'; END IF; IF NOT EXISTS(SELECT 1 FROM courses WHERE id=p_course_id AND status='approved') THEN RAISE EXCEPTION 'active course required'; END IF; INSERT INTO offering_proposals(proposer_user_id,course_id,academic_year,semester,section,instructor_name) VALUES(auth.user_id()::uuid,p_course_id,p_academic_year,btrim(p_semester),btrim(p_section),p_instructor_name) RETURNING id INTO v_id; RETURN v_id; END $$;
--> statement-breakpoint
CREATE FUNCTION api.list_my_offering_proposals() RETURNS TABLE(id uuid,course_id uuid,academic_year integer,semester text,section text,instructor_name text,status text,created_at timestamptz) LANGUAGE sql SECURITY DEFINER SET search_path=app_private,pg_temp AS $$ SELECT id,course_id,academic_year,semester,section,instructor_name,status,created_at FROM offering_proposals WHERE proposer_user_id=auth.user_id()::uuid ORDER BY created_at DESC $$;
--> statement-breakpoint
CREATE FUNCTION api.resolve_offering_proposal(p_proposal_id uuid,p_approve boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=app_private,pg_temp AS $$ DECLARE p offering_proposals%ROWTYPE; BEGIN PERFORM app_private.require_administrator(); SELECT * INTO p FROM offering_proposals WHERE id=p_proposal_id AND status='pending' FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'pending proposal not found'; END IF; IF p_approve AND NOT EXISTS(SELECT 1 FROM offerings WHERE course_id=p.course_id AND academic_year=p.academic_year AND semester=p.semester AND section=p.section) THEN INSERT INTO offerings(course_id,academic_year,semester,section,instructor_name,status) VALUES(p.course_id,p.academic_year,p.semester,p.section,p.instructor_name,'approved'); END IF; UPDATE offering_proposals SET status=CASE WHEN p_approve THEN 'approved' ELSE 'rejected' END,resolved_by=auth.user_id()::uuid,resolved_at=now() WHERE id=p_proposal_id; END $$;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION api.create_offering_proposal(uuid,integer,text,text,text),api.list_my_offering_proposals(),api.resolve_offering_proposal(uuid,boolean) TO authenticated;
